services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: empldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
    ports:
       - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - emplnetwork
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  empl-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: empl_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/empldb
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - emplnetwork
    restart: unless-stopped
networks:
  emplnetwork:
    driver: bridge
